on:
  push:
    branches:
    - master
  pull_request:

name: Build & Test

jobs:
  build-test-deploy:
    environment: GooglePlay publish
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        channel: 'stable'
        flutter-version: "2.0.5"

    - run: |
        echo $JK_STORE_FILE | base64 -d > android/app/lib_key.jks
      env:
        JK_STORE_FILE: ${{ secrets.JK_STORE_FILE }}
      name: set environment from secrets

    - run: |
        flutter --version
        flutter pub get
        # flutter analyze
        flutter test
      name: run tests

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7'

    - uses: maierj/fastlane-action@v2.0.1
      name: build android
      with:
        skip-tracking: true
        lane: 'build_android'
        subdirectory: 'android'
        bundle-install-path: 'vendor/bundle'
      env:
        JK_PASSWORD: ${{ secrets.JK_PASSWORD }}
        JK_ALIAS: "key"
        JK_STORE_PASSWORD: ${{ secrets.JK_STORE_PASSWORD }}
        SUPPLY_JSON_KEY_DATA: ${{ secrets.SUPPLY_JSON_KEY_DATA }}
        KEY_PATH: lib_key.jks

    - uses: maierj/fastlane-action@v2.0.1
      if: ${{ github.ref == 'refs/heads/master' }}
      name: deploy to PlayStore
      with:
        skip-tracking: true
        lane: 'push_to_ps_internal'
        subdirectory: 'android'
        bundle-install-path: 'vendor/bundle'
      env:
        JK_PASSWORD: ${{ secrets.JK_PASSWORD }}
        JK_ALIAS: "key"
        JK_STORE_PASSWORD: ${{ secrets.JK_STORE_PASSWORD }}
        SUPPLY_JSON_KEY_DATA: ${{ secrets.SUPPLY_JSON_KEY_DATA }}
        KEY_PATH: lib_key.jks

